FROM openjdk:11-jdk-slim-bullseye AS build-env

COPY . /app
WORKDIR /app
RUN ./mvnw clean package

FROM gcr.io/distroless/java11-debian11
COPY --from=build-env /app/target/*jar /app/app.jar
WORKDIR /app
CMD ["app.jar"]
